name: Build

on:
  pull_request:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Free up disk space in runner
      uses: ./.github/actions/disk-cleanup

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        cache-read-only: true

    - name: Build Docker image
      run: docker build -f Dockerfile.java -t libsignal-builder .

    - name: Build library inside Docker
      run: |
        docker run \
          -v "$HOME/.gradle/caches:/.gradle-ro-cache:ro" \
          libsignal-builder build
